# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: node:12
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: /bin/bash e2e/setup.sh
      - run: yarn e2e

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  deploy:
    docker:
      - image: node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "yarn.lock" }}
            - npm-cache
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn build
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - run:
          name: Publish
          command: |
            yarn publish

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
